name: "Run Aptos CLI e2e tests"
on:
  # This is called from within the docker-build-test.yaml workflow since we depend
  # on the images having been built before this workflow runs. You can see in
  # the invocation of the test suite that we pass in the image repo we just
  # built and pushed the tools image to and the git SHA1 of the commit / PR
  # that triggered this workflow.
  workflow_call:
    inputs:
      GIT_SHA:
        required: true
        type: string
        description: Use this to override the git SHA1, branch name (e.g. devnet) or tag to release the SDK from

jobs:
  # Run the Aptos CLI examples. We run the CLI on this commit / PR against a
  # local testnet using the devnet, testnet, and mainnet branches. This way
  # we ensure that the Aptos CLI works with all 3 prod networks, at least
  # based on the tests in the test suite.
  run-cli-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - uses: ./.github/actions/gar-auth
        with:
          GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}

      # Run CLI tests against local testnet built from devnet branch.
      - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
        name: devnet-tests
        with:
          max_attempts: 5
          timeout_minutes: 20
          command: cd ./crates/aptos/e2e && python main.py --base-network devnet --image-repo-with-project ${{ secrets.GCP_DOCKER_ARTIFACT_REPO }} --test-cli-tag ${{ inputs.GIT_SHA }} --working-directory ${{ runner.temp }}/aptos-e2e-tests

      # Run CLI tests against local testnet built from testnet branch.
      - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
        name: testnet-tests
        with:
          max_attempts: 5
          timeout_minutes: 20
          command: cd ./crates/aptos/e2e && python main.py --base-network testnet --image-repo-with-project ${{ secrets.GCP_DOCKER_ARTIFACT_REPO }} --test-cli-tag ${{ inputs.GIT_SHA }} --working-directory ${{ runner.temp }}/aptos-e2e-tests

      # Run CLI tests against local testnet built from mainnet branch.
      - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
        name: mainnet-tests
        with:
          max_attempts: 5
          timeout_minutes: 20
          command: cd ./crates/aptos/e2e && python main.py --base-network testnet --image-repo-with-project ${{ secrets.GCP_DOCKER_ARTIFACT_REPO }} --test-cli-tag ${{ inputs.GIT_SHA }} --working-directory ${{ runner.temp }}/aptos-e2e-tests
